build_from:
  aarch64: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity-aarch64:latest
  amd64: registry.cn-hangzhou.aliyuncs.com/arcw/sgcc_electricity-amd64:latest
codenotary:
  base_image: ARC-MX@github.com
  signer: ARC-MX@github.com
