build_from:
  aarch64: registry.cn-hangzhou.aliyuncs.com/arcw/aarch64-sgcc_electricity:latest
  amd64: registry.cn-hangzhou.aliyuncs.com/arcw/amd64-sgcc_electricity:latest
codenotary:
  base_image: ARC-MX@github.com
  signer: ARC-MX@github.com
