FROM python:3.9-slim-bullseye as build

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY scripts/* /app/
COPY requirements-armv7.txt /tmp/requirements-armv7.txt

RUN apt-get --allow-releaseinfo-change update \
    && apt-get install -y --no-install-recommends jq chromium curl chromium-driver tzdata \
    && apt-get install libgl1-mesa-glx libgomp1 libglib2.0-0 libdatrie1 libgraphite2-3 libswresample3 libcairo2 libchromaprint1 libopenjp2-7 libtiff5 libvorbisenc2 libvorbisfile3 libgdk-pixbuf2.0-0 libgsm1 libxcb-shm0 libaom0 libopus0 libswscale5 libwavpack1 libxvidcore4 libvdpau1 libjbig0 libgfortran5 libshine3 libspeex1 libvorbis0a libmpg123-0 libtwolame0 libssh-gcrypt-4  libpangoft2-1.0-0 libpango-1.0-0 libatlas3-base  libogg0 libsoxr0 libva2  libwebpmux3 libbluray2 libxcb-render0  libzvbi0 libavutil56 libmp3lame0 libxfixes3 libharfbuzz0b libavcodec58 libwebp6 libopenmpt0 libva-drm2 libva-x11-2 librsvg2-2 libtheora0 libsnappy1v5 libdrm2 libavformat58 libpixman-1-0 libfontconfig1 libthai0 libxrender1 libgme0 libpangocairo-1.0-0 liblcms2-2 -y \
    && ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure --frontend noninteractive tzdata \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN cd /tmp \
    && pip config --global set global.extra-index-url https://www.piwheels.org/simple \
    && python3 -m pip install --upgrade pip \
    && curl -O -L https://github.com/nknytk/built-onnxruntime-for-raspberrypi-linux/raw/master/wheels/buster/onnxruntime-1.8.1-cp39-cp39-linux_armv7l.whl \
    && PIP_ROOT_USER_ACTION=ignore pip3 install onnxruntime-1.8.1-cp39-cp39-linux_armv7l.whl \
    && PIP_ROOT_USER_ACTION=ignore pip3 install \
    --disable-pip-version-check \
    --no-cache-dir \
    -r requirements-armv7.txt \
    && rm -rf /tmp/* \
    && pip cache purge \
    && rm -rf /var/log/*


ENV LANG C.UTF-8

CMD ["python"]